# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
