# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
